// =======================================create new user============================================
###
POST http://localhost:3003/api/login
content-type: application/json

 {
    "username": "mostafa",
    "password": "12345"
}