

// ===================================get all persons================================================
###
GET http://localhost:3001/api/persons


// =======================================create new person============================================
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "mostafa bamoos",
  "number": "0600000000"
}

// =======================================update person============================================
###
PUT http://localhost:3001/api/persons/68e6896684a67645dd046027
content-type: application/json

{
  "name": "mostafa Update",
  "number": "0600000000"
}


// ================================get item person by id===================================================
###
GET http://localhost:3001/api/persons/68e6896684a67645dd046027


// =====================================delete person==============================================
###
DELETE http://localhost:3001/api/persons/68e6a96585da1c0ff530c341


// =================================get info statisique==================================================
###
GET http://localhost:3001/info